### ISSUE TITLE
The comparison seems to be outdated.

### ISSUE THREAD

**Issue by gregthwuen** [ocelotpotpie/FreedomChat#36]
In the comparison section in the README, the following is said regarding [NoEncryption](https://github.com/Doclic/NoEncryption):

> Unlike NoEncryption, FreedomChat does not create invalid chat packets. NoEncryption will cause a large and visible warning to players on 1.19.1. FreedomChat will not do this, and instead only show a small grey bar. This is because while NoEncryption strips the signature from player chat packets, FreedomChat reconstructs player chat as if it were coming from the server itself, which is never signed (and thus not reportable).

But in recent versions (I believe since the [4.0 release](https://github.com/Doclic/NoEncryption/releases/tag/4.0-real)), NoEncryption seems to work the same way as this plugin, you can even see the gray bars in the screenshot in its [README](https://github.com/Doclic/NoEncryption/blob/258d2ed921e717114be6a4537ae91247eb24063b/README.md):

> ![Screenshot showing a minecraft chat between players with a gray bar on the left side](https://user-images.githubusercontent.com/79623093/223909733-979c8cdf-faa5-499d-afe3-4bd1fef8a7ac.png)

So, what's still differentiating this plugin from NoEncryption? Is it only the option to advertise the "Safe Server" status to the No Chat Reports Mod? I think the README should be updated accordingly.

**Comment by e-im** [comment]
I hadn't really followed either of these plugins.

I've removed the comparison section.
