### ISSUE TITLE
Online (UUID) user account, on 1.20.1 offline server getting kicked when he types /say <something> command; potentially more

### ISSUE THREAD

**Issue by TheJoshue** [ocelotpotpie/FreedomChat#37]
The title of this post gives half the description of what is happening.

Basically:
- have an offline 1.20.1 server (mine is: `Paper version git-Paper-183 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb60bff)`)
- use FastLogin or any similar plugin that makes available to specific user to use their premium account (by that having online UUID on the server)
- as 1.20.1 player, on 1.20.1 offline server, running FreedomChat plugin, execute `/say hi` command

considering all steps above, this happens:
![image](https://github.com/e-im/FreedomChat/assets/56804505/5df91269-73bf-45db-9b07-6f3a804e19fb)

**Comment by e-im** [comment]
FastLogin/the like aren't going to be supported by me with this plugin. PRs welcome if its a quick/nonintrusive fix but this is a nofix from me.
