### ISSUE TITLE
1.20.6 Update

### ISSUE THREAD

**Issue by supertakeru** [ocelotpotpie/FreedomChat#49]
Update needed for 1.20.6 release.

**Comment by pop4959** [comment]
I forgot to get back around to this, was going to update it once Paper had updated to 1.20 but that happened on a weekday.

Expect builds soon.

**Comment by pop4959** [comment]
Closed by 33e92244c51545ec913e599882552b9651c7c8f0

**Comment by supertakeru** [comment]
when will you release builds? sorry its been two weeks

**Comment by pop4959** [comment]
GitHub Actions has builds available if you need one it's just not on Modrinth yet

**Comment by supertakeru** [comment]
> GitHub Actions has builds available if you need one it's just not on Modrinth yet

Why is that? Does it still need further changes or you just haven't got the chance?

**Comment by pop4959** [comment]
No just waiting for it to be uploaded, ocelot hasn't had a chance to yet. I am simply stating that there are already builds available though.
