### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by fucksophie** [ocelotpotpie/FreedomChat#51]
This plugin locks itself down to protocol versions, so a 1.21 version has to be supported explicitly.

**Comment by pop4959** [comment]
Thanks, already well aware. We should have it updated by Monday (at least here through GitHub Actions). Modrinth builds usually come later.

**Comment by pop4959** [comment]
Also since there aren't many changes in 1.21 it should be easy to change the protocol version in the source code and re-compile if you need it sooner. I just want to make sure to thoroughly test this before releasing a build and I haven't had a chance yet.

**Comment by pop4959** [comment]
I've gone ahead and bumped the protocol version, but since Paper is not released yet for 1.21, this is provided only for convenience, as it is entirely untested.

**Comment by MisterSheeple** [comment]
I'm testing it now and the rewrite-chat function doesn't seem to work.

**Comment by Bobcat00** [comment]
Using FreedomChat # 18 from GitHub Actions, the "Chat messages can't be verified" toast still pops up.

Plugin seems to work properly otherwise.

Paper version 1.21-40-master@b45d9b6 (2024-07-01T08:23:14Z)
FreedomChat version 1.6.0
Mojang Client 1.21
enforce-secure-profile=false

Config:
```
# Whether FreedomChat should replace player (signed or unsigned) chat with
# system messages. This is what makes chat not reportable.
rewrite-chat: true

# Whether FreedomChat should claim to clients that secure chat is enforced.
# With this set to true, the "Chat messages can't be verified" toast will not
# be shown. This is, in default configurations, unrelated to allowing clients
# not signing their messages join.
claim-secure-chat-enforced: true

# Whether to report the server as secure (disabling chat reporting) to the
# NoChatReports client mod. This displays a green icon on the server list
# screen and if enforce-secure-profiles is disabled the open chat screen
# for users of the client-side mod.
send-prevents-chat-reports-to-client: false
```

**Comment by pop4959** [comment]
Since Paper is now out, went and tested this again compiling against 1.21. Everything appears to be working.

Do note again that the `claim-secure-chat-enforced` configuration option no longer exists, so seeing a "Chat messages can't be verified" toast is intended and correct behavior.
