### ISSUE TITLE
send-prevents-chat-reports-to-client not working

### ISSUE THREAD

**Issue by Brottweiler** [ocelotpotpie/FreedomChat#53]
Does `send-prevents-chat-reports-to-client` still work? In 1.20.6 and 1.21 my experience is that the icon does not show up in the server list. It shows up on a 1.20.4 server however.

**Comment by pop4959** [comment]
In theory it's still supported as we re-write this packet to include the `preventsChatReports` field for mods that accept that. Unless that isn't working, or something else changed here. I will admit I am not really familiar with this, so it has not really been tested thoroughly, and it's entirely possible it could be broken, though no one has complained yet about it until now.

It would help me out if you can explain what you are doing to see this icon in the server list, and how it differs between older versions and the current version.

**Comment by Brottweiler** [comment]
I am running `No Chat Reports Fabric-1.21-v2.8.0` on the client and FreedomChat on the server. I run the latest version for 1.20.4, 1.20.6 and 1.21 respectively (1.21 version I took from GitHub actions). The icon in the server list shows up only for the 1.20.4 server (and all previous versions in the past), but since 1.20.6 the icon will not show up in the server list. 

I am using 1.21 on the client, with ViaFabricPlus, which makes me able to join the 1.20.4 server. But the 1.20.4 server also runs ViaVersion so I can join with 1.21 even without ViaFabricPlus, but the point is that the icon still shows up for the 1.20.4 server just fine. 

I hope that helps.

**Comment by pop4959** [comment]
Yeah I don't think it's used by many people. I did specifically update this to maintain the feature when we updated to 1.20.6 though, so if it broke, that'd be when. I'll take a look when I get a chance (or if anyone else would like to before I end getting around to this, feel free).

**Comment by CompeyDev** [comment]
Yep, facing this too. Please lmk when this is fixed!

**Comment by pop4959** [comment]
@Brottweiler @CompeyDev Please check and confirm that this works for you in the latest build - should be fixed now thanks to @whiler-sesame finding the issue here.

**Comment by CompeyDev** [comment]
Can confirm - it works!

**Comment by Brottweiler** [comment]
All good now. Thanks!
