### ISSUE TITLE
Plugin not working on 1.21.1

### ISSUE THREAD

**Issue by TuckerAndrews3** [ocelotpotpie/FreedomChat#59]
Just letting you guys know the plugin won't load on 1.21.1 paper, if you want I can provide the error.

**Comment by pop4959** [comment]
Provide the error.

**Comment by TuckerAndrews3** [comment]
Hey I just have to say I am so sorry I have a lot of plugins to keep track of and misread thinking this plugin was not loading but it was. Apologies! Thank you for upkeeping a fantastic plugin.

**Comment by pop4959** [comment]
No problem, glad to hear you found a solution.
