### ISSUE TITLE
Require No Chat Reports on client

### ISSUE THREAD

**Issue by NyaomiDEV** [ocelotpotpie/FreedomChat#61]
I wanted to make extra sure that the only people joining in my Paper server have NCR installed. This can be achieved if I have NCR on a Fabric server, but there's no way to have it on Paper.

I wonder if this can be added here.

**Comment by pop4959** [comment]
This sounds like a feature request for No Chat Reports - this is FreedomChat. I would recommend making a feature request on their issue tracker instead. We don't have any reason to support this on our end.

**Comment by NyaomiDEV** [comment]
> This sounds like a feature request for No Chat Reports - this is FreedomChat. I would recommend making a feature request on their issue tracker instead. We don't have any reason to support this on our end.

I understand. Thing is, FreedomChat is the only "adjacent" plugin on PaperMC, and No Chat Reports doesn't have a Paper version as of now. Asking for this to them means asking them to make a port with the same functionality as FreedomChat plus this one thing.

**Comment by pop4959** [comment]
Yep, 100% understand. This is generally something that we don't care about supporting however, especially given NCR is not even required on the client to begin with, and FreedomChat does not require any client-side mods to be installed itself. For the most part it's entirely redundant.
