### ISSUE TITLE
Toast notification still appearing

### ISSUE THREAD

**Issue by Rhydium** [ocelotpotpie/FreedomChat#63]
Hi there,

I just installed `FreedomChat-1.5.2.jar` in my 1.20.4 Paper server. In the config hiding of the toast notification is set to `true` but the toast notification is still shown. `enforce-secure-profile` is set to `false` in the `server.properties`.

There's no errors in the console.

Edit: 
The only console output provided by the plugin is `[21:52:47 INFO]: [FreedomChat] Enabling FreedomChat v1.5.2`.

**Comment by pop4959** [comment]
You're using an outdated version of Paper which is no longer supported.

This is not a bug, as that option did not exist in 1.5.2, and was re-introduced in 1.6.1 or later. There are currently no plans to backport the change, however you're welcome to do so yourself if you'd like.
