### ISSUE TITLE
New version update

### ISSUE THREAD

**Issue by cL3v3r47** [ocelotpotpie/FreedomChat#67]
Can you update this plugin for Paper 1.21.4?

**Comment by pop4959** [comment]
It already works, you just need to set the system property that ignores the protocol version.

I've gone ahead and bumped it though so if you download the latest you shouldn't need that.

**Comment by cL3v3r47** [comment]
How do I do that?

**Comment by pop4959** [comment]
Download it from GitHub actions in the top navigation bar or wait for ocelot to release it on Modrinth sometime later.

**Comment by cL3v3r47** [comment]
Thanks

**Comment by ocelotpotpie** [comment]
FYI: Version has been updated on Modrinth: https://modrinth.com/plugin/freedomchat
